spring.application.name=produtos-api
spring.profiles.default=dev

app.jwt.secret=chave-super-segura-para-jwt-com-no-minimo-32-bytes
app.jwt.expiration-ms=3600000
app.cors.allowed-origins=http://localhost:3000

